### ISSUE TITLE
Error with google drive on a cluster system

### ISSUE THREAD

**Issue by jribado** [smangul1/rop#67] opened 2016-05-25 00:52 UTC
v. 1.01

--microbiome option does not register
python install.py --immune works fine

python install.py --standard
Standard installation option selected
Downloading the database (~65GB) takes up to 45 minute
Please wait until the installation is completed.
Downloading the database files
--2016-05-24 17:49:13--  https://googledrive.com/host/0B_NUyiE86yDwaUxoVjhlSjN5SkE/database.tar
Resolving googledrive.com... 216.58.195.225, 2607:f8b0:4005:806::2001
Connecting to googledrive.com|216.58.195.225|:443... connected.
ERROR: certificate common name "*.googleusercontent.com" doesn't match requested host name "googledrive.com".
To connect to googledrive.com insecurely, use '--no-check-certificate'.
Checking md5sum of the databases
md5sum: ./database.tar: No such file or directory
Traceback (most recent call last):
  File "install.py", line 35, in <module>
    checksum_downloaded = downloaded.communicate()[0].split()[0]
IndexError: list index out of range

**Comment by smangul1** [comment] 2016-05-25 00:56
Thanks for pointing this out. We are investigating the issue

**Comment by harrydgnt** [comment] 2016-05-25 03:41
I can't seem to find resolutions related to this issue with google drive. 

I will add an option for manual installation when the download fails, if --no-check-certificate fixes. 

I will give you an update as I update it

**Comment by harrydgnt** [comment] 2016-06-05 04:44
Hello. I fixed ad google support suggested. 

However, I was not able to reproduce the error in my systems so I cannot be certain that it works for your system. 

It would be great if you run the updated installation script and let us know if it works! 

Thank you very much for your help

**Comment by jribado** [comment] 2016-06-06 16:57
It works! ...Or at least the database is downloading for now - will update if any issues arise. Thank you!

**Comment by harrydgnt** [comment] 2016-06-08 02:12
I am closing this issue now. Let me know if there is an error!

**Closed by harrydgnt** 2016-06-08 02:12 UTC
Labels: help wanted
